import React, { useMemo, useState } from "react";
import { ArrowRight, Check, CreditCard, Heart, Menu, Minus, Package, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Trash2, Truck, Upload, X } from "lucide-react";

const products = [
  {id:1,name:"Convite Aurora em Papel Texturizado",category:"Convites",price:9.9,old:12.5,badge:"Mais vendido",mark:"A & M",tone:"rose",description:"Convite elegante com envelope, impressão personalizada e acabamento artesanal."},
  {id:2,name:"Manual dos Padrinhos Essência",category:"Padrinhos",price:18.9,badge:"Personalizável",mark:"Padrinhos",tone:"sage",description:"Manual personalizado com informações da cerimônia, traje e recado especial."},
  {id:3,name:"Convite Virtual Interativo",category:"Itens digitais",price:79.9,old:99.9,badge:"Entrega digital",mark:"Save the date",tone:"pink",description:"Convite digital com botões para confirmação, localização, presentes e WhatsApp."},
  {id:4,name:"Menu Individual Jardim",category:"Papelaria",price:4.5,badge:"Novo",mark:"Menu",tone:"green",description:"Menu individual para composição de mesa, disponível em diferentes papéis."},
  {id:5,name:"Kit Toalete Celebrare",category:"Papelaria",price:64.9,badge:"Kit completo",mark:"Celebre",tone:"sand",description:"Itens coordenados para deixar cada detalhe da celebração especial."},
  {id:6,name:"Identidade Visual do Evento",category:"Identidade visual",price:159.9,old:189.9,badge:"Exclusivo",mark:"Sua história",tone:"gold",description:"Criação de monograma, paleta, tipografia e elementos visuais para o evento."}
];
const categories=["Todos","Convites","Padrinhos","Itens digitais","Papelaria","Identidade visual"];
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function ProductArt({p,big=false}){return <div className={`product-art ${p.tone} ${big?'big':''}`}><div className="invite"><b>✦</b><strong>{p.mark}</strong><i/><small>GRAFIART CONVITERIA</small></div></div>}
function App(){
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(""),[cat,setCat]=useState("Todos"),[cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[selected,setSelected]=useState(null),[liked,setLiked]=useState([]),[toast,setToast]=useState("");
 const filtered=useMemo(()=>products.filter(p=>(cat==="Todos"||p.category===cat)&&(`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[cat,query]);
 const count=cart.reduce((a,x)=>a+x.qty,0),subtotal=cart.reduce((a,x)=>a+x.qty*x.price,0);
 const add=p=>{setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]);setToast("Produto adicionado à sacola");setTimeout(()=>setToast(""),1800)};
 const qty=(id,n)=>setCart(c=>n<1?c.filter(x=>x.id!==id):c.map(x=>x.id===id?{...x,qty:n}:x));
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
 return <div>
  {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  <div className="topbar">Frete para todo o Brasil • Produção artesanal em Charqueadas/RS</div>
  <header><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><button className="brand" onClick={()=>go('inicio')}><span>G</span><div><b>Grafiart</b><small>CONVITERIA</small></div></button>
   <nav><button onClick={()=>go('inicio')}>Início</button><button onClick={()=>go('produtos')}>Produtos</button><button onClick={()=>go('digitais')}>Itens digitais</button><button onClick={()=>go('sobre')}>Nossa história</button><button onClick={()=>go('contato')}>Contato</button></nav>
   <div className="actions"><button className="icon" onClick={()=>setSearch(!search)}><Search/></button><button className="icon bag" onClick={()=>setCartOpen(true)}><ShoppingBag/>{count>0&&<em>{count}</em>}</button></div>
  </header>
  {search&&<div className="search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por convites, menus, padrinhos..."/><button onClick={()=>setSearch(false)}><X/></button></div>}
  <main>
   <section id="inicio" className="hero"><div className="heroText"><span className="eyebrow"><Sparkles size={14}/> Papelaria personalizada para celebrar</span><h1>Detalhes que contam a sua história.</h1><p>Convites, identidade visual e papelaria afetiva criados para transformar o seu evento em uma memória inesquecível.</p><div className="cta"><button className="primary" onClick={()=>go('produtos')}>Conheça a coleção <ArrowRight/></button><button className="secondary" onClick={()=>go('contato')}>Solicitar projeto personalizado</button></div><div className="trust"><span><ShieldCheck/>Compra segura</span><span><Truck/>Envio nacional</span><span><Heart/>Feito com carinho</span></div></div><div className="heroArt"><div className="envelope"/><div className="heroInvite"><strong>E & L</strong><i/><small>VAMOS CELEBRAR O AMOR</small><b>18 • 10 • 2026</b><em>❧</em></div><div className="float"><Heart fill="currentColor"/><span><small>Produção</small><b>100% personalizada</b></span></div></div></section>
   <section className="benefits">{[[Package,"Produção cuidadosa","Cada pedido feito com atenção"],[CreditCard,"Pagamento facilitado","Pix, boleto e cartão"],[Truck,"Entrega para todo Brasil","Acompanhe seu pedido"],[ShieldCheck,"Compra protegida","Seus dados sempre seguros"]].map(([I,t,d])=><div key={t}><I/><span><b>{t}</b><small>{d}</small></span></div>)}</section>
   <section id="produtos" className="products"><div className="sectionTitle"><small>ESCOLHIDOS COM CARINHO</small><h2>Produtos em destaque</h2><p>Peças que unem delicadeza, personalidade e acabamento especial.</p></div><div className="filters">{categories.map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="grid">{filtered.map(p=><article key={p.id}><button className="artButton" onClick={()=>setSelected(p)}><ProductArt p={p}/><label>{p.badge}</label></button><div className="productInfo"><div className="productHead"><span><small>{p.category}</small><button onClick={()=>setSelected(p)}>{p.name}</button></span><button className="heart" onClick={()=>setLiked(l=>l.includes(p.id)?l.filter(i=>i!==p.id):[...l,p.id])}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/></button></div><div className="buy"> <span>{p.old&&<del>{money(p.old)}</del>}<b>{money(p.price)} <small>/ un.</small></b></span><button className="primary" onClick={()=>add(p)}>Comprar</button></div></div></article>)}</div>{!filtered.length&&<p className="empty">Nenhum produto encontrado.</p>}</section>
   <section id="digitais" className="digital"><div className="phones"><div/><div className="phone"><small>CONVITE VIRTUAL</small><b>Beatriz<br/>&<br/>Lucas</b><span>18 de outubro de 2026</span><button>Confirmar presença</button></div></div><div><small>PRÁTICO, ELEGANTE E SUSTENTÁVEL</small><h2>Convites digitais que encantam e conectam.</h2><p>Compartilhe sua celebração com um convite interativo, personalizado e pronto para enviar pelo WhatsApp.</p>{["Confirmação de presença integrada","Localização do evento em um toque","Lista de presentes e recados","Entrega rápida e sem custo de frete"].map(x=><span className="check" key={x}><Check/>{x}</span>)}<button className="gold" onClick={()=>{setCat('Itens digitais');go('produtos')}}>Ver modelos digitais <ArrowRight/></button></div></section>
   <section id="sobre" className="about"><div className="aboutCard"><span>G</span><h2>Feito à mão,<br/>pensado para você.</h2><i/><p>Atendimento próximo, criação afetiva e atenção em cada acabamento.</p></div><div><small>NOSSA HISTÓRIA</small><h2>Transformamos sonhos em papel e celebrações em memória.</h2><p>A Grafiart Conviteria nasceu do amor pelos detalhes. Em nosso ateliê em Charqueadas, no Rio Grande do Sul, criamos papelaria personalizada para casamentos, festas de 15 anos e momentos especiais.</p><div className="stats"><span><b>+900</b><small>pessoas na comunidade</small></span><span><b>Todo BR</b><small>entrega nacional</small></span><span><b>100%</b><small>personalizado</small></span></div></div></section>
   <section className="reviews"><div className="sectionTitle"><small>QUEM COMPRA, RECOMENDA</small><h2>Histórias que fazem parte da nossa</h2></div><div>{[["O convite ficou ainda mais lindo do que imaginávamos. Atendimento atencioso do início ao fim!","Mariana & Felipe"],["A identidade visual deixou tudo conectado e delicado. Recebemos muitos elogios.","Camila & Rafael"],["O convite virtual foi super prático e elegante. A confirmação ajudou muito.","Laura & Bruno"]].map(([t,a])=><article key={a}><span>{[1,2,3,4,5].map(i=><Star key={i} fill="currentColor"/>)}</span><p>“{t}”</p><b>{a}</b></article>)}</div></section>
   <section id="contato" className="contact"><div><small>COMECE A PLANEJAR</small><h2>Vamos criar algo inesquecível para o seu grande dia?</h2><p>Conte um pouco sobre seu evento e receba atendimento personalizado.</p><a href="https://api.whatsapp.com/send/?phone=5551996149298" target="_blank">Falar pelo WhatsApp</a></div></section>
  </main>
  <footer><div><div className="brand footerBrand"><span>G</span><div><b>Grafiart</b><small>CONVITERIA</small></div></div><p>Papelaria personalizada para tornar cada celebração única.</p><a href="https://www.instagram.com/convites.grafiart" target="_blank">@convites.grafiart</a></div><div><b>Navegue</b><p>Início</p><p>Produtos</p><p>Itens digitais</p></div><div><b>Ajuda</b><p>Prazos e entregas</p><p>Trocas e devoluções</p><p>Política de privacidade</p></div><div><b>Receba novidades</b><p>Inspirações e lançamentos.</p><div className="newsletter"><input placeholder="Seu melhor e-mail"/><button><ArrowRight/></button></div></div></footer><div className="copyright">© 2026 Grafiart Conviteria. Demonstração visual.</div>
  {menu&&<><div className="overlay" onClick={()=>setMenu(false)}/><aside className="mobileMenu"><button onClick={()=>setMenu(false)}><X/></button><h2>Grafiart</h2>{[['Início','inicio'],['Produtos','produtos'],['Itens digitais','digitais'],['Nossa história','sobre'],['Contato','contato']].map(([t,id])=><button key={id} onClick={()=>go(id)}>{t}</button>)}</aside></>}
  {cartOpen&&<><div className="overlay" onClick={()=>setCartOpen(false)}/><aside className="drawer"><div className="drawerTitle"><span><h2>Sua sacola</h2><small>{count} {count===1?'item':'itens'}</small></span><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="cartItems">{!cart.length?<div className="cartEmpty"><ShoppingBag/><h3>Sua sacola está vazia</h3><p>Descubra peças especiais para seu evento.</p></div>:cart.map(x=><div className="cartItem" key={x.id}><div className={`thumb ${x.tone}`}/><span><b>{x.name}</b><small>{money(x.price)}</small><div><button onClick={()=>qty(x.id,x.qty-1)}><Minus/></button><em>{x.qty}</em><button onClick={()=>qty(x.id,x.qty+1)}><Plus/></button></div></span><button onClick={()=>qty(x.id,0)}><Trash2/></button></div>)}</div>{cart.length>0&&<div className="checkout"><span>Subtotal <b>{money(subtotal)}</b></span><small>Frete calculado na próxima etapa.</small><button className="primary" onClick={()=>setToast('Demonstração pronta para integrar ao checkout')}>Ir para o checkout <ArrowRight/></button></div>}</aside></>}
  {selected&&<><div className="overlay" onClick={()=>setSelected(null)}/><div className="modal"><button className="modalClose" onClick={()=>setSelected(null)}><X/></button><ProductArt p={selected} big/><div className="modalInfo"><small>{selected.category}</small><h2>{selected.name}</h2><div className="stars">{[1,2,3,4,5].map(i=><Star key={i} fill="currentColor"/>)}</div><p>{selected.description}</p><b className="price">{money(selected.price)}</b><label>Personalização do pedido</label><textarea placeholder="Informe nomes, data, cores e detalhes do evento..."/><button className="upload"><Upload/> Enviar imagem de referência</button><button className="primary wide" onClick={()=>{add(selected);setSelected(null);setCartOpen(true)}}>Adicionar à sacola</button></div></div></>}
 </div>
}
export default App;